// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.6
// source: internal/proto/accounting.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CounterEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityHash    uint64                 `protobuf:"fixed64,1,opt,name=entity_hash,json=entityHash,proto3" json:"entity_hash,omitempty"`
	Hits          uint64                 `protobuf:"varint,2,opt,name=hits,proto3" json:"hits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CounterEntry) Reset() {
	*x = CounterEntry{}
	mi := &file_internal_proto_accounting_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CounterEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CounterEntry) ProtoMessage() {}

func (x *CounterEntry) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_accounting_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CounterEntry.ProtoReflect.Descriptor instead.
func (*CounterEntry) Descriptor() ([]byte, []int) {
	return file_internal_proto_accounting_proto_rawDescGZIP(), []int{0}
}

func (x *CounterEntry) GetEntityHash() uint64 {
	if x != nil {
		return x.EntityHash
	}
	return 0
}

func (x *CounterEntry) GetHits() uint64 {
	if x != nil {
		return x.Hits
	}
	return 0
}

type CounterBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderId      uint64                 `protobuf:"varint,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Timestamp     uint64                 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Entries       []*CounterEntry        `protobuf:"bytes,3,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CounterBatch) Reset() {
	*x = CounterBatch{}
	mi := &file_internal_proto_accounting_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CounterBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CounterBatch) ProtoMessage() {}

func (x *CounterBatch) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_accounting_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CounterBatch.ProtoReflect.Descriptor instead.
func (*CounterBatch) Descriptor() ([]byte, []int) {
	return file_internal_proto_accounting_proto_rawDescGZIP(), []int{1}
}

func (x *CounterBatch) GetSenderId() uint64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *CounterBatch) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *CounterBatch) GetEntries() []*CounterEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_internal_proto_accounting_proto protoreflect.FileDescriptor

const file_internal_proto_accounting_proto_rawDesc = "" +
	"\n" +
	"\x1finternal/proto/accounting.proto\x12\x06drl.v1\"C\n" +
	"\fCounterEntry\x12\x1f\n" +
	"\ventity_hash\x18\x01 \x01(\x06R\n" +
	"entityHash\x12\x12\n" +
	"\x04hits\x18\x02 \x01(\x04R\x04hits\"y\n" +
	"\fCounterBatch\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\x04R\bsenderId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x04R\ttimestamp\x12.\n" +
	"\aentries\x18\x03 \x03(\v2\x14.drl.v1.CounterEntryR\aentriesB'Z%github.com/gchiesa/drl/internal/protob\x06proto3"

var (
	file_internal_proto_accounting_proto_rawDescOnce sync.Once
	file_internal_proto_accounting_proto_rawDescData []byte
)

func file_internal_proto_accounting_proto_rawDescGZIP() []byte {
	file_internal_proto_accounting_proto_rawDescOnce.Do(func() {
		file_internal_proto_accounting_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_accounting_proto_rawDesc), len(file_internal_proto_accounting_proto_rawDesc)))
	})
	return file_internal_proto_accounting_proto_rawDescData
}

var file_internal_proto_accounting_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_proto_accounting_proto_goTypes = []any{
	(*CounterEntry)(nil), // 0: drl.v1.CounterEntry
	(*CounterBatch)(nil), // 1: drl.v1.CounterBatch
}
var file_internal_proto_accounting_proto_depIdxs = []int32{
	0, // 0: drl.v1.CounterBatch.entries:type_name -> drl.v1.CounterEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_proto_accounting_proto_init() }
func file_internal_proto_accounting_proto_init() {
	if File_internal_proto_accounting_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_accounting_proto_rawDesc), len(file_internal_proto_accounting_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_proto_accounting_proto_goTypes,
		DependencyIndexes: file_internal_proto_accounting_proto_depIdxs,
		MessageInfos:      file_internal_proto_accounting_proto_msgTypes,
	}.Build()
	File_internal_proto_accounting_proto = out.File
	file_internal_proto_accounting_proto_goTypes = nil
	file_internal_proto_accounting_proto_depIdxs = nil
}
