// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.6
// source: internal/proto/accounting.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CounterEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityHash    uint64                 `protobuf:"fixed64,1,opt,name=entity_hash,json=entityHash,proto3" json:"entity_hash,omitempty"`
	Hits          uint64                 `protobuf:"varint,2,opt,name=hits,proto3" json:"hits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CounterEntry) Reset() {
	*x = CounterEntry{}
	mi := &file_internal_proto_accounting_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CounterEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CounterEntry) ProtoMessage() {}

func (x *CounterEntry) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_accounting_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CounterEntry.ProtoReflect.Descriptor instead.
func (*CounterEntry) Descriptor() ([]byte, []int) {
	return file_internal_proto_accounting_proto_rawDescGZIP(), []int{0}
}

func (x *CounterEntry) GetEntityHash() uint64 {
	if x != nil {
		return x.EntityHash
	}
	return 0
}

func (x *CounterEntry) GetHits() uint64 {
	if x != nil {
		return x.Hits
	}
	return 0
}

type CounterBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderId      uint64                 `protobuf:"varint,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Timestamp     uint64                 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Entries       []*CounterEntry        `protobuf:"bytes,3,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CounterBatch) Reset() {
	*x = CounterBatch{}
	mi := &file_internal_proto_accounting_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CounterBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CounterBatch) ProtoMessage() {}

func (x *CounterBatch) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_accounting_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CounterBatch.ProtoReflect.Descriptor instead.
func (*CounterBatch) Descriptor() ([]byte, []int) {
	return file_internal_proto_accounting_proto_rawDescGZIP(), []int{1}
}

func (x *CounterBatch) GetSenderId() uint64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *CounterBatch) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *CounterBatch) GetEntries() []*CounterEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type BlockEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	TtlNanos      int64                  `protobuf:"varint,2,opt,name=ttl_nanos,json=ttlNanos,proto3" json:"ttl_nanos,omitempty"`
	EntityIp      string                 `protobuf:"bytes,3,opt,name=entity_ip,json=entityIp,proto3" json:"entity_ip,omitempty"`
	EntityPath    string                 `protobuf:"bytes,4,opt,name=entity_path,json=entityPath,proto3" json:"entity_path,omitempty"`
	EntityHdrs    map[string]string      `protobuf:"bytes,5,rep,name=entity_hdrs,json=entityHdrs,proto3" json:"entity_hdrs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockEvent) Reset() {
	*x = BlockEvent{}
	mi := &file_internal_proto_accounting_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockEvent) ProtoMessage() {}

func (x *BlockEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_accounting_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockEvent.ProtoReflect.Descriptor instead.
func (*BlockEvent) Descriptor() ([]byte, []int) {
	return file_internal_proto_accounting_proto_rawDescGZIP(), []int{2}
}

func (x *BlockEvent) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *BlockEvent) GetTtlNanos() int64 {
	if x != nil {
		return x.TtlNanos
	}
	return 0
}

func (x *BlockEvent) GetEntityIp() string {
	if x != nil {
		return x.EntityIp
	}
	return ""
}

func (x *BlockEvent) GetEntityPath() string {
	if x != nil {
		return x.EntityPath
	}
	return ""
}

func (x *BlockEvent) GetEntityHdrs() map[string]string {
	if x != nil {
		return x.EntityHdrs
	}
	return nil
}

type UnblockEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnblockEvent) Reset() {
	*x = UnblockEvent{}
	mi := &file_internal_proto_accounting_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnblockEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnblockEvent) ProtoMessage() {}

func (x *UnblockEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_accounting_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnblockEvent.ProtoReflect.Descriptor instead.
func (*UnblockEvent) Descriptor() ([]byte, []int) {
	return file_internal_proto_accounting_proto_rawDescGZIP(), []int{3}
}

func (x *UnblockEvent) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// BlockEventWithExpiresAt is the successor to BlockEvent that carries an absolute
// expiration timestamp (Unix nanoseconds) instead of a relative TTL. This avoids
// clock-skew drift when the event is relayed across nodes: the sender computes
// "now + ttl" once and all receivers apply exactly the same deadline.
type BlockEventWithExpiresAt struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Key            string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	ExpiresAtNanos int64                  `protobuf:"varint,2,opt,name=expires_at_nanos,json=expiresAtNanos,proto3" json:"expires_at_nanos,omitempty"` // Unix nanoseconds (time.Time.UnixNano)
	EntityIp       string                 `protobuf:"bytes,3,opt,name=entity_ip,json=entityIp,proto3" json:"entity_ip,omitempty"`
	EntityPath     string                 `protobuf:"bytes,4,opt,name=entity_path,json=entityPath,proto3" json:"entity_path,omitempty"`
	EntityHdrs     map[string]string      `protobuf:"bytes,5,rep,name=entity_hdrs,json=entityHdrs,proto3" json:"entity_hdrs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BlockEventWithExpiresAt) Reset() {
	*x = BlockEventWithExpiresAt{}
	mi := &file_internal_proto_accounting_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockEventWithExpiresAt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockEventWithExpiresAt) ProtoMessage() {}

func (x *BlockEventWithExpiresAt) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_accounting_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockEventWithExpiresAt.ProtoReflect.Descriptor instead.
func (*BlockEventWithExpiresAt) Descriptor() ([]byte, []int) {
	return file_internal_proto_accounting_proto_rawDescGZIP(), []int{4}
}

func (x *BlockEventWithExpiresAt) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *BlockEventWithExpiresAt) GetExpiresAtNanos() int64 {
	if x != nil {
		return x.ExpiresAtNanos
	}
	return 0
}

func (x *BlockEventWithExpiresAt) GetEntityIp() string {
	if x != nil {
		return x.EntityIp
	}
	return ""
}

func (x *BlockEventWithExpiresAt) GetEntityPath() string {
	if x != nil {
		return x.EntityPath
	}
	return ""
}

func (x *BlockEventWithExpiresAt) GetEntityHdrs() map[string]string {
	if x != nil {
		return x.EntityHdrs
	}
	return nil
}

type HandoverPayload struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SenderId          uint64                 `protobuf:"varint,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Timestamp         uint64                 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	CompressedEntries []byte                 `protobuf:"bytes,3,opt,name=compressed_entries,json=compressedEntries,proto3" json:"compressed_entries,omitempty"` // zstd-compressed protobuf CounterBatch
	EntityCount       uint64                 `protobuf:"varint,4,opt,name=entity_count,json=entityCount,proto3" json:"entity_count,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HandoverPayload) Reset() {
	*x = HandoverPayload{}
	mi := &file_internal_proto_accounting_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandoverPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandoverPayload) ProtoMessage() {}

func (x *HandoverPayload) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_accounting_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandoverPayload.ProtoReflect.Descriptor instead.
func (*HandoverPayload) Descriptor() ([]byte, []int) {
	return file_internal_proto_accounting_proto_rawDescGZIP(), []int{5}
}

func (x *HandoverPayload) GetSenderId() uint64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *HandoverPayload) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HandoverPayload) GetCompressedEntries() []byte {
	if x != nil {
		return x.CompressedEntries
	}
	return nil
}

func (x *HandoverPayload) GetEntityCount() uint64 {
	if x != nil {
		return x.EntityCount
	}
	return 0
}

type DrlMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Content:
	//
	//	*DrlMessage_Counters
	//	*DrlMessage_Block
	//	*DrlMessage_Unblock
	//	*DrlMessage_Handover
	//	*DrlMessage_BlockWithExpiresAt
	Content       isDrlMessage_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DrlMessage) Reset() {
	*x = DrlMessage{}
	mi := &file_internal_proto_accounting_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrlMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrlMessage) ProtoMessage() {}

func (x *DrlMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_accounting_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrlMessage.ProtoReflect.Descriptor instead.
func (*DrlMessage) Descriptor() ([]byte, []int) {
	return file_internal_proto_accounting_proto_rawDescGZIP(), []int{6}
}

func (x *DrlMessage) GetContent() isDrlMessage_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *DrlMessage) GetCounters() *CounterBatch {
	if x != nil {
		if x, ok := x.Content.(*DrlMessage_Counters); ok {
			return x.Counters
		}
	}
	return nil
}

func (x *DrlMessage) GetBlock() *BlockEvent {
	if x != nil {
		if x, ok := x.Content.(*DrlMessage_Block); ok {
			return x.Block
		}
	}
	return nil
}

func (x *DrlMessage) GetUnblock() *UnblockEvent {
	if x != nil {
		if x, ok := x.Content.(*DrlMessage_Unblock); ok {
			return x.Unblock
		}
	}
	return nil
}

func (x *DrlMessage) GetHandover() *HandoverPayload {
	if x != nil {
		if x, ok := x.Content.(*DrlMessage_Handover); ok {
			return x.Handover
		}
	}
	return nil
}

func (x *DrlMessage) GetBlockWithExpiresAt() *BlockEventWithExpiresAt {
	if x != nil {
		if x, ok := x.Content.(*DrlMessage_BlockWithExpiresAt); ok {
			return x.BlockWithExpiresAt
		}
	}
	return nil
}

type isDrlMessage_Content interface {
	isDrlMessage_Content()
}

type DrlMessage_Counters struct {
	Counters *CounterBatch `protobuf:"bytes,1,opt,name=counters,proto3,oneof"`
}

type DrlMessage_Block struct {
	Block *BlockEvent `protobuf:"bytes,2,opt,name=block,proto3,oneof"`
}

type DrlMessage_Unblock struct {
	Unblock *UnblockEvent `protobuf:"bytes,3,opt,name=unblock,proto3,oneof"`
}

type DrlMessage_Handover struct {
	Handover *HandoverPayload `protobuf:"bytes,4,opt,name=handover,proto3,oneof"`
}

type DrlMessage_BlockWithExpiresAt struct {
	BlockWithExpiresAt *BlockEventWithExpiresAt `protobuf:"bytes,5,opt,name=block_with_expires_at,json=blockWithExpiresAt,proto3,oneof"`
}

func (*DrlMessage_Counters) isDrlMessage_Content() {}

func (*DrlMessage_Block) isDrlMessage_Content() {}

func (*DrlMessage_Unblock) isDrlMessage_Content() {}

func (*DrlMessage_Handover) isDrlMessage_Content() {}

func (*DrlMessage_BlockWithExpiresAt) isDrlMessage_Content() {}

var File_internal_proto_accounting_proto protoreflect.FileDescriptor

const file_internal_proto_accounting_proto_rawDesc = "" +
	"\n" +
	"\x1finternal/proto/accounting.proto\x12\x06drl.v1\"C\n" +
	"\fCounterEntry\x12\x1f\n" +
	"\ventity_hash\x18\x01 \x01(\x06R\n" +
	"entityHash\x12\x12\n" +
	"\x04hits\x18\x02 \x01(\x04R\x04hits\"y\n" +
	"\fCounterBatch\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\x04R\bsenderId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x04R\ttimestamp\x12.\n" +
	"\aentries\x18\x03 \x03(\v2\x14.drl.v1.CounterEntryR\aentries\"\xfd\x01\n" +
	"\n" +
	"BlockEvent\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1b\n" +
	"\tttl_nanos\x18\x02 \x01(\x03R\bttlNanos\x12\x1b\n" +
	"\tentity_ip\x18\x03 \x01(\tR\bentityIp\x12\x1f\n" +
	"\ventity_path\x18\x04 \x01(\tR\n" +
	"entityPath\x12C\n" +
	"\ventity_hdrs\x18\x05 \x03(\v2\".drl.v1.BlockEvent.EntityHdrsEntryR\n" +
	"entityHdrs\x1a=\n" +
	"\x0fEntityHdrsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\" \n" +
	"\fUnblockEvent\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"\xa4\x02\n" +
	"\x17BlockEventWithExpiresAt\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12(\n" +
	"\x10expires_at_nanos\x18\x02 \x01(\x03R\x0eexpiresAtNanos\x12\x1b\n" +
	"\tentity_ip\x18\x03 \x01(\tR\bentityIp\x12\x1f\n" +
	"\ventity_path\x18\x04 \x01(\tR\n" +
	"entityPath\x12P\n" +
	"\ventity_hdrs\x18\x05 \x03(\v2/.drl.v1.BlockEventWithExpiresAt.EntityHdrsEntryR\n" +
	"entityHdrs\x1a=\n" +
	"\x0fEntityHdrsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9e\x01\n" +
	"\x0fHandoverPayload\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\x04R\bsenderId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x04R\ttimestamp\x12-\n" +
	"\x12compressed_entries\x18\x03 \x01(\fR\x11compressedEntries\x12!\n" +
	"\fentity_count\x18\x04 \x01(\x04R\ventityCount\"\xb6\x02\n" +
	"\n" +
	"DrlMessage\x122\n" +
	"\bcounters\x18\x01 \x01(\v2\x14.drl.v1.CounterBatchH\x00R\bcounters\x12*\n" +
	"\x05block\x18\x02 \x01(\v2\x12.drl.v1.BlockEventH\x00R\x05block\x120\n" +
	"\aunblock\x18\x03 \x01(\v2\x14.drl.v1.UnblockEventH\x00R\aunblock\x125\n" +
	"\bhandover\x18\x04 \x01(\v2\x17.drl.v1.HandoverPayloadH\x00R\bhandover\x12T\n" +
	"\x15block_with_expires_at\x18\x05 \x01(\v2\x1f.drl.v1.BlockEventWithExpiresAtH\x00R\x12blockWithExpiresAtB\t\n" +
	"\acontentB'Z%github.com/gchiesa/drl/internal/protob\x06proto3"

var (
	file_internal_proto_accounting_proto_rawDescOnce sync.Once
	file_internal_proto_accounting_proto_rawDescData []byte
)

func file_internal_proto_accounting_proto_rawDescGZIP() []byte {
	file_internal_proto_accounting_proto_rawDescOnce.Do(func() {
		file_internal_proto_accounting_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_accounting_proto_rawDesc), len(file_internal_proto_accounting_proto_rawDesc)))
	})
	return file_internal_proto_accounting_proto_rawDescData
}

var file_internal_proto_accounting_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_internal_proto_accounting_proto_goTypes = []any{
	(*CounterEntry)(nil),            // 0: drl.v1.CounterEntry
	(*CounterBatch)(nil),            // 1: drl.v1.CounterBatch
	(*BlockEvent)(nil),              // 2: drl.v1.BlockEvent
	(*UnblockEvent)(nil),            // 3: drl.v1.UnblockEvent
	(*BlockEventWithExpiresAt)(nil), // 4: drl.v1.BlockEventWithExpiresAt
	(*HandoverPayload)(nil),         // 5: drl.v1.HandoverPayload
	(*DrlMessage)(nil),              // 6: drl.v1.DrlMessage
	nil,                             // 7: drl.v1.BlockEvent.EntityHdrsEntry
	nil,                             // 8: drl.v1.BlockEventWithExpiresAt.EntityHdrsEntry
}
var file_internal_proto_accounting_proto_depIdxs = []int32{
	0, // 0: drl.v1.CounterBatch.entries:type_name -> drl.v1.CounterEntry
	7, // 1: drl.v1.BlockEvent.entity_hdrs:type_name -> drl.v1.BlockEvent.EntityHdrsEntry
	8, // 2: drl.v1.BlockEventWithExpiresAt.entity_hdrs:type_name -> drl.v1.BlockEventWithExpiresAt.EntityHdrsEntry
	1, // 3: drl.v1.DrlMessage.counters:type_name -> drl.v1.CounterBatch
	2, // 4: drl.v1.DrlMessage.block:type_name -> drl.v1.BlockEvent
	3, // 5: drl.v1.DrlMessage.unblock:type_name -> drl.v1.UnblockEvent
	5, // 6: drl.v1.DrlMessage.handover:type_name -> drl.v1.HandoverPayload
	4, // 7: drl.v1.DrlMessage.block_with_expires_at:type_name -> drl.v1.BlockEventWithExpiresAt
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_internal_proto_accounting_proto_init() }
func file_internal_proto_accounting_proto_init() {
	if File_internal_proto_accounting_proto != nil {
		return
	}
	file_internal_proto_accounting_proto_msgTypes[6].OneofWrappers = []any{
		(*DrlMessage_Counters)(nil),
		(*DrlMessage_Block)(nil),
		(*DrlMessage_Unblock)(nil),
		(*DrlMessage_Handover)(nil),
		(*DrlMessage_BlockWithExpiresAt)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_accounting_proto_rawDesc), len(file_internal_proto_accounting_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_proto_accounting_proto_goTypes,
		DependencyIndexes: file_internal_proto_accounting_proto_depIdxs,
		MessageInfos:      file_internal_proto_accounting_proto_msgTypes,
	}.Build()
	File_internal_proto_accounting_proto = out.File
	file_internal_proto_accounting_proto_goTypes = nil
	file_internal_proto_accounting_proto_depIdxs = nil
}
