// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.6
// source: internal/proto/channel.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ChannelMessage is the envelope for events exchanged over the persistent,
// hi-priority gRPC channel established between cluster members when a node
// joins the cluster. Like DrlMessage, it carries an explicit type
// discriminator via oneof so new hi-priority event kinds can be multiplexed
// onto the same channel in the future without breaking the wire format or
// requiring a new RPC.
type ChannelMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Content:
	//
	//	*ChannelMessage_BlockWithExpiresAt
	//	*ChannelMessage_Unblock
	Content       isChannelMessage_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelMessage) Reset() {
	*x = ChannelMessage{}
	mi := &file_internal_proto_channel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelMessage) ProtoMessage() {}

func (x *ChannelMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_channel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelMessage.ProtoReflect.Descriptor instead.
func (*ChannelMessage) Descriptor() ([]byte, []int) {
	return file_internal_proto_channel_proto_rawDescGZIP(), []int{0}
}

func (x *ChannelMessage) GetContent() isChannelMessage_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ChannelMessage) GetBlockWithExpiresAt() *BlockEventWithExpiresAt {
	if x != nil {
		if x, ok := x.Content.(*ChannelMessage_BlockWithExpiresAt); ok {
			return x.BlockWithExpiresAt
		}
	}
	return nil
}

func (x *ChannelMessage) GetUnblock() *UnblockEvent {
	if x != nil {
		if x, ok := x.Content.(*ChannelMessage_Unblock); ok {
			return x.Unblock
		}
	}
	return nil
}

type isChannelMessage_Content interface {
	isChannelMessage_Content()
}

type ChannelMessage_BlockWithExpiresAt struct {
	BlockWithExpiresAt *BlockEventWithExpiresAt `protobuf:"bytes,1,opt,name=block_with_expires_at,json=blockWithExpiresAt,proto3,oneof"`
}

type ChannelMessage_Unblock struct {
	Unblock *UnblockEvent `protobuf:"bytes,2,opt,name=unblock,proto3,oneof"`
}

func (*ChannelMessage_BlockWithExpiresAt) isChannelMessage_Content() {}

func (*ChannelMessage_Unblock) isChannelMessage_Content() {}

var File_internal_proto_channel_proto protoreflect.FileDescriptor

const file_internal_proto_channel_proto_rawDesc = "" +
	"\n" +
	"\x1cinternal/proto/channel.proto\x12\x06drl.v1\x1a\x1finternal/proto/accounting.proto\"\xa3\x01\n" +
	"\x0eChannelMessage\x12T\n" +
	"\x15block_with_expires_at\x18\x01 \x01(\v2\x1f.drl.v1.BlockEventWithExpiresAtH\x00R\x12blockWithExpiresAt\x120\n" +
	"\aunblock\x18\x02 \x01(\v2\x14.drl.v1.UnblockEventH\x00R\aunblockB\t\n" +
	"\acontent2Q\n" +
	"\x11PersistentChannel\x12<\n" +
	"\x06Stream\x12\x16.drl.v1.ChannelMessage\x1a\x16.drl.v1.ChannelMessage(\x010\x01B'Z%github.com/gchiesa/drl/internal/protob\x06proto3"

var (
	file_internal_proto_channel_proto_rawDescOnce sync.Once
	file_internal_proto_channel_proto_rawDescData []byte
)

func file_internal_proto_channel_proto_rawDescGZIP() []byte {
	file_internal_proto_channel_proto_rawDescOnce.Do(func() {
		file_internal_proto_channel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_channel_proto_rawDesc), len(file_internal_proto_channel_proto_rawDesc)))
	})
	return file_internal_proto_channel_proto_rawDescData
}

var file_internal_proto_channel_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_proto_channel_proto_goTypes = []any{
	(*ChannelMessage)(nil),          // 0: drl.v1.ChannelMessage
	(*BlockEventWithExpiresAt)(nil), // 1: drl.v1.BlockEventWithExpiresAt
	(*UnblockEvent)(nil),            // 2: drl.v1.UnblockEvent
}
var file_internal_proto_channel_proto_depIdxs = []int32{
	1, // 0: drl.v1.ChannelMessage.block_with_expires_at:type_name -> drl.v1.BlockEventWithExpiresAt
	2, // 1: drl.v1.ChannelMessage.unblock:type_name -> drl.v1.UnblockEvent
	0, // 2: drl.v1.PersistentChannel.Stream:input_type -> drl.v1.ChannelMessage
	0, // 3: drl.v1.PersistentChannel.Stream:output_type -> drl.v1.ChannelMessage
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_proto_channel_proto_init() }
func file_internal_proto_channel_proto_init() {
	if File_internal_proto_channel_proto != nil {
		return
	}
	file_internal_proto_accounting_proto_init()
	file_internal_proto_channel_proto_msgTypes[0].OneofWrappers = []any{
		(*ChannelMessage_BlockWithExpiresAt)(nil),
		(*ChannelMessage_Unblock)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_channel_proto_rawDesc), len(file_internal_proto_channel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_channel_proto_goTypes,
		DependencyIndexes: file_internal_proto_channel_proto_depIdxs,
		MessageInfos:      file_internal_proto_channel_proto_msgTypes,
	}.Build()
	File_internal_proto_channel_proto = out.File
	file_internal_proto_channel_proto_goTypes = nil
	file_internal_proto_channel_proto_depIdxs = nil
}
