// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.6
// source: internal/proto/channel.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PersistentChannel_Stream_FullMethodName = "/drl.v1.PersistentChannel/Stream"
)

// PersistentChannelClient is the client API for PersistentChannel service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PersistentChannel is a bidirectional streaming RPC used to propagate
// hi-priority events between two cluster members over a single, long-lived
// gRPC connection instead of an on-demand connection per event.
//
// Exactly one stream is established per unordered pair of nodes: the dial
// direction is decided deterministically by comparing node addresses (see
// internal/membership/channel.go), and both peers Send and Recv on that same
// stream. This halves the number of live connections compared to a model
// where each node dials the other independently.
type PersistentChannelClient interface {
	Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ChannelMessage, ChannelMessage], error)
}

type persistentChannelClient struct {
	cc grpc.ClientConnInterface
}

func NewPersistentChannelClient(cc grpc.ClientConnInterface) PersistentChannelClient {
	return &persistentChannelClient{cc}
}

func (c *persistentChannelClient) Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ChannelMessage, ChannelMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PersistentChannel_ServiceDesc.Streams[0], PersistentChannel_Stream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChannelMessage, ChannelMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PersistentChannel_StreamClient = grpc.BidiStreamingClient[ChannelMessage, ChannelMessage]

// PersistentChannelServer is the server API for PersistentChannel service.
// All implementations must embed UnimplementedPersistentChannelServer
// for forward compatibility.
//
// PersistentChannel is a bidirectional streaming RPC used to propagate
// hi-priority events between two cluster members over a single, long-lived
// gRPC connection instead of an on-demand connection per event.
//
// Exactly one stream is established per unordered pair of nodes: the dial
// direction is decided deterministically by comparing node addresses (see
// internal/membership/channel.go), and both peers Send and Recv on that same
// stream. This halves the number of live connections compared to a model
// where each node dials the other independently.
type PersistentChannelServer interface {
	Stream(grpc.BidiStreamingServer[ChannelMessage, ChannelMessage]) error
	mustEmbedUnimplementedPersistentChannelServer()
}

// UnimplementedPersistentChannelServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPersistentChannelServer struct{}

func (UnimplementedPersistentChannelServer) Stream(grpc.BidiStreamingServer[ChannelMessage, ChannelMessage]) error {
	return status.Error(codes.Unimplemented, "method Stream not implemented")
}
func (UnimplementedPersistentChannelServer) mustEmbedUnimplementedPersistentChannelServer() {}
func (UnimplementedPersistentChannelServer) testEmbeddedByValue()                           {}

// UnsafePersistentChannelServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PersistentChannelServer will
// result in compilation errors.
type UnsafePersistentChannelServer interface {
	mustEmbedUnimplementedPersistentChannelServer()
}

func RegisterPersistentChannelServer(s grpc.ServiceRegistrar, srv PersistentChannelServer) {
	// If the following call panics, it indicates UnimplementedPersistentChannelServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PersistentChannel_ServiceDesc, srv)
}

func _PersistentChannel_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PersistentChannelServer).Stream(&grpc.GenericServerStream[ChannelMessage, ChannelMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PersistentChannel_StreamServer = grpc.BidiStreamingServer[ChannelMessage, ChannelMessage]

// PersistentChannel_ServiceDesc is the grpc.ServiceDesc for PersistentChannel service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PersistentChannel_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "drl.v1.PersistentChannel",
	HandlerType: (*PersistentChannelServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _PersistentChannel_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "internal/proto/channel.proto",
}
